base_config: config/criteo_x1
base_expid: combined_pair_posw0.1_logloss
dataset_id: criteo_x1

tuner_space:
    model_root: './Criteo/combined_pair_logloss_tuner'
    pos_weight: [0.2,0.4,0.6,0.8,1]
    