base_config: config/criteo_x1
base_expid: DCNv2_criteo_x1_posw1
dataset_id: criteo_x1

tuner_space:
    model_root: './Criteo/DCNv2_criteo_x1_posw'
    pos_weight: [0.1,0.2,0.4,0.6,0.8,1]
    seed: [2020,2021,2022,2023,2024]

    