base_config: config/criteo_x1
base_expid: DCNv2_criteo_x1_posw0.1_sample_0.5
dataset_id: criteo_x1_0.5

tuner_space:
    model_root: './Criteo/DCNv2_criteo_x1_posw0.1_sample_0.5'
    seed: [2020,2021,2022,2023,2024]

    