base_config: config/criteo_x1
base_expid: DCNv2_criteo_x1_posw0.1_combined_list_alpha1
dataset_id: criteo_x1
# DCNv2_criteo_x1_posw0.1_combined_list_alpha1_022_a84528f4
tuner_space:
    model_root: './Criteo/DCNv2_criteo_x1_posw0.1_combined_list_alpha0.9'
    seed: [2020,2021,2022,2023,2024]
    alpha: 0.9

    